apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: interaxo
spec:
  description: Interaxo team
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
