apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 02-interaxo
spec:
  destination:
    name: ""
    namespace: 02-interaxo
    server: "https://kubernetes.default.svc"
  source:
    path: envs/se-prod-01/02-interaxo
    repoURL: "https://github.com/pavel-kurnosov/envs"
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
