apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-se
namePrefix: prod-

resources:
  - ../../applications/interaxo

components:
  - ../../variants/se

patchesStrategicMerge:
  - deployment.yml
  - version.yml
  - settings.yml
