apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 01-interaxo
namePrefix: prod-

resources:
  - ../../../applications/interaxo
  - ../../../applications/quarkus

components:
  - ../../../variants/se

patchesStrategicMerge:
  - deployment.yml
  - version.yml
  - settings.yml

patches:
  - target:
      kind: Ingress
      name: interaxo-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: /01-interaxo
  - target:
      kind: Application
      name: quarkus
    patch: |-
      - op: add
        path: /spec/source/helm/valueFiles/-
        value: $values/envs/se-prod-01/01-interaxo/quarkus-values.yaml
patchesJson6902:
  - target:
      kind: Application
      name: quarkus
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: argocd
