apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 02-interaxo
namePrefix: prod-

resources:
  - ../../../applications/interaxo
  - ../../../applications/quarkus-helm

components:
  - ../../../variants/se

patchesStrategicMerge:
  - deployment.yml
  - version.yml
  - settings.yml

patches:
  - target:
      kind: Ingress
      name: interaxo-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: /02-interaxo
