apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus
spec:
  project: interaxo
  sources:
    - chart: quarkus
      repoURL: https://redhat-developer.github.io/redhat-helm-charts
      targetRevision: 0.0.3
      helm:
        valueFiles:
          - values.yaml
    - repoURL: "https://github.com/pavel-kurnosov/envs.git"
      targetRevision: HEAD
      ref: repo
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
