apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus
spec:
  project: interaxo
  sources:
    - chart: quarkus
      repoURL: https://redhat-developer.github.io/redhat-helm-charts
      targetRevision: 0.0.3
      helm:
        valueFiles:
          - values.yaml
    - repoURL: $ARGOCD_APP_SOURCE_REPO_URL
      targetRevision: HEAD
      ref: repo
  destination:
    server: "https://kubernetes.default.svc"
