apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus
spec:
  project: default
  source:
    chart: quarkus
    repoURL: https://redhat-developer.github.io/redhat-helm-charts
    targetRevision: 0.0.3
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
